version: '{build}'
os: Visual Studio 2017
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: ObMCktoYTWmEAsA8Khx4nllZEQxs/RqVS/9AkVxBXyml5zJXByQ/odckmKWblpYe
branches:
  only:
    - master
build_script:
- ps: >-
    ./Build.ps1

    nuget pack nuspec/Nito.Comparers.nuspec

    nuget pack nuspec/Comparers.nuspec

    nuget pack nuspec/Comparers.Ix.nuspec

    nuget pack nuspec/Comparers.Rx.nuspec
test_script:
- ps: ./Coverage.ps1
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    appveyor_repo_tag: true